export default place = [
  {
    id: "0",
    name: "LE KD Restaurant",
    description : 'this is an amazing restaurant for your daily meal',
    adresse: "Manouba , Tunis ",
    type: "Restaurant",
    tel : "",
    siteWeb:"www.thekdRestaurant.com",
    rating: "4.4",
    nbtable:'100',
    img: require("../assets/images/food/food2.jpg"),
  },
  {
    id: "1",
    name: "LE KD Restaurant",
    description : 'this is an amazing restaurant for your daily meal',
    adresse: "Manouba , Tunis ",
    type: "Restaurant",
    tel : "",
    siteWeb:"www.thekdRestaurant.com",
    rating: "4.4",
    nbtable:'100',
    img: require("../assets/images/food/food2.jpg"),
  },
  {  
      id: "2",
  name: "LE KD Restaurant",
  description : 'this is an amazing restaurant for your daily meal',
  adresse: "Manouba , Tunis ",
  type: "Restaurant",
  tel : "",
  siteWeb:"www.thekdRestaurant.com",
  rating: "4.4",
  nbtable:'100',
  img: require("../assets/images/food/food2.jpg"),
  },
  {    id: "3",
  name: "LE KD Restaurant",
  description : 'this is an amazing restaurant for your daily meal',
  adresse: "Manouba , Tunis ",
  type: "Restaurant",
  tel : "",
  siteWeb:"www.thekdRestaurant.com",
  rating: "4.4",
  nbtable:'100',
  img: require("../assets/images/food/food2.jpg"),
  },

  {    id: "4",
  name: "LE KD Restaurant",
  description : 'this is an amazing restaurant for your daily meal',
  adresse: "Manouba , Tunis ",
  type: "Restaurant",
  tel : "",
  siteWeb:"www.thekdRestaurant.com",
  rating: "4.4",
  nbtable:'100',
  img: require("../assets/images/food/food2.jpg"),
  },
  {
    id: "5",
    name: "LE KD Restaurant",
    description : 'this is an amazing restaurant for your daily meal',
    adresse: "Manouba , Tunis ",
    type: "Restaurant",
    tel : "",
    siteWeb:"www.thekdRestaurant.com",
    rating: "4.4",
    nbtable:'100',
    img: require("../assets/images/food/food2.jpg"),
  },
];
