export default place = [
  {
    id: "0",
    name: "LE KD Restaurant",
    description : 'this is an amazing restaurant for your daily meal',
    adresse: "Manouba , Tunis ",
    type: "Restaurant",
    tel : "",
    siteWeb:"www.thekdRestaurant.com",
    rating: "4.4",
    nbtable:'100',
    img: require("../assets/images/food/food2.jpg"),
    nbCompte : '',
    liked: 'true',
    utilisateur :{
      'userId':'0',
    }
  },
  {
    id: "1",
    name: "The Big Dip",
    description : 'this is an amazing restaurant for your daily meal',
    adresse: "Manouba , Tunis ",
    type: "Restaurant",
    tel : "",
    siteWeb:"www.thekdRestaurant.com",
    rating: "4.4",
    nbtable:'100',
    img: require("../assets/images/food/food6.jpg"),
    liked: 'true',
  },
  {  
      id: "2",
  name: "LE Grand Chef",
  description : 'this is an amazing restaurant for your daily meal',
  adresse: "Manouba , Tunis ",
  type: "Restaurant",
  tel : "",
  siteWeb:"www.thekdRestaurant.com",
  rating: "4.4",
  nbtable:'100',
  img: require("../assets/images/food/food4.jpg"),
  liked: 'true',
  },
  {    id: "3",
  name: "Restaurant La Goulette",
  description : 'this is an amazing restaurant for your daily meal',
  adresse: "Manouba , Tunis ",
  type: "Restaurant",
  tel : "",
  siteWeb:"www.thekdRestaurant.com",
  rating: "4.4",
  nbtable:'100',
  img: require("../assets/images/food/food1.jpg"),
  liked: 'false',
  },

  {    id: "4",
  name: "LE KD Restaurant",
  description : 'this is an amazing restaurant for your daily meal',
  adresse: "Manouba , Tunis ",
  type: "Restaurant",
  tel : "",
  siteWeb:"www.thekdRestaurant.com",
  rating: "4.4",
  nbtable:'100',
  img: require("../assets/images/food/food5.jpg"),
  liked: 'true',
  },
  {
    id: "5",
    name: "LE KD Restaurant",
    description : 'this is an amazing restaurant for your daily meal',
    adresse: "Manouba , Tunis ",
    type: "Restaurant",
    tel : "",
    siteWeb:"www.thekdRestaurant.com",
    rating: "4.4",
    nbtable:'100',
    img: require("../assets/images/food/food4.jpg"),
    liked: 'false',
  },
];
